FROM ubuntu:18.04
LABEL email="forky.blockchain.anonymized.for.submission@gmail.com"
LABEL description="Docker environment for Bitcoin v0.13.0"
RUN apt-get update
RUN apt-get install -y lsb-release software-properties-common
RUN apt-get clean all
RUN apt-get install -y curl tar wget
RUN curl -LO https://apt.llvm.org/llvm.sh
RUN chmod +x llvm.sh
RUN ./llvm.sh 13
ENV clang /usr/bin/clang-13
ENV clang++ /usr/bin/clang++-13
RUN curl -LO https://bitcoincore.org/bin/bitcoin-core-0.13.0/bitcoin-0.13.0.tar.gz
RUN tar -zxvf bitcoin-0.13.0.tar.gz 
RUN mv bitcoin-0.13.0 bitcoin
WORKDIR bitcoin
RUN apt-get install -y gcc g++ build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
RUN apt-get install -y libevent-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev
RUN apt-get install -y libsqlite3-dev libzmq3-dev libboost-thread-dev libssl-dev libboost-all-dev
#RUN ./contrib/install_db4.sh `pwd`
RUN ./autogen.sh
RUN CC=/usr/bin/clang-13 CXX=/usr/bin/clang++-13 ./configure --disable-wallet --without-gui
RUN make -j 8
